version: '3'
services: 
  xrayr: 
    image: ghcr.io/xrayr-project/xrayr:master
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
    restart: always
    container_name: xrayr
    network_mode: host
